# Generated by Django 5.2 on 2025-05-31 22:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('plano_status', models.BooleanField(default=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('condicoes_medicas', models.CharField(blank=True, max_length=255, null=True)),
                ('ciclo_menstrual', models.CharField(blank=True, max_length=100, null=True)),
                ('medicamentos', models.CharField(blank=True, max_length=255, null=True)),
                ('lesoes', models.CharField(blank=True, max_length=255, null=True)),
                ('ocupacao', models.CharField(blank=True, max_length=100, null=True)),
                ('estilo_vida', models.CharField(blank=True, max_length=100, null=True)),
                ('pratica_esportes', models.CharField(blank=True, max_length=100, null=True)),
                ('pratica_exercicios', models.CharField(blank=True, max_length=100, null=True)),
                ('dias_disponiveis', models.CharField(blank=True, max_length=100, null=True)),
                ('horario_preferencia', models.CharField(blank=True, max_length=100, null=True)),
                ('exercicio_preferencia', models.CharField(blank=True, max_length=100, null=True)),
                ('info_adicional', models.CharField(blank=True, max_length=255, null=True)),
                ('tempo_atual_treino', models.CharField(blank=True, max_length=100, null=True)),
                ('tempo_destreinado', models.CharField(blank=True, max_length=100, null=True)),
                ('tempo_treino_anterior', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('categoria', models.CharField(default='aquecimento', max_length=50)),
                ('grupo_muscular', models.CharField(default='trapezius', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da Avaliação')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Peso (kg)')),
                ('massa_muscular', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Massa Muscular (kg)')),
                ('gordura_percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Gordura (%)')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Altura (m)')),
                ('peitoral', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Peitoral (cm)')),
                ('cintura', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Cintura (cm)')),
                ('abdomen', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Abdômen (cm)')),
                ('quadril', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Quadril (cm)')),
                ('braco_direito', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Braço Direito (cm)')),
                ('braco_esquerdo', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Braço Esquerdo (cm)')),
                ('antebraco_direito', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Antebraço Direito (cm)')),
                ('antebraco_esquerdo', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Antebraço Esquerdo (cm)')),
                ('coxa_direita', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Coxa Direita (cm)')),
                ('coxa_esquerda', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Coxa Esquerda (cm)')),
                ('panturrilha_direita', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Panturrilha Direita (cm)')),
                ('panturrilha_esquerda', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Panturrilha Esquerda (cm)')),
                ('dobra_peitoral', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Dobra Peitoral (mm)')),
                ('dobra_subescapular', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Dobra Subescapular (mm)')),
                ('dobra_axilar', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Dobra Axilar Média (mm)')),
                ('dobra_triceps', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Dobra Tríceps (mm)')),
                ('dobra_abdominal', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Dobra Abdominal (mm)')),
                ('dobra_suprailiaca', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Dobra Supra Ilíaca (mm)')),
                ('dobra_coxa', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Dobra Coxa (mm)')),
                ('postural_pescoco', models.CharField(blank=True, max_length=100, verbose_name='Postural Pescoço')),
                ('postural_ombro', models.CharField(blank=True, max_length=100, verbose_name='Postural Ombro')),
                ('postural_quadril', models.CharField(blank=True, max_length=100, verbose_name='Postural Quadril')),
                ('postural_joelho', models.CharField(blank=True, max_length=100, verbose_name='Postural Joelho')),
                ('postural_tornozelo', models.CharField(blank=True, max_length=100, verbose_name='Postural Tornozelo')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='avaliacoes_fotos/', verbose_name='Foto da Avaliação')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pages.aluno')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='plano_tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pages.plano'),
        ),
        migrations.CreateModel(
            name='SeriePersonalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('anotacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinos', to='Pages.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='ExercicioTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('carga', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('reps', models.IntegerField(blank=True, null=True)),
                ('desejadas', models.IntegerField(blank=True, null=True)),
                ('descanso', models.CharField(blank=True, max_length=50)),
                ('sets', models.IntegerField(blank=True, null=True)),
                ('set1', models.CharField(blank=True, max_length=50)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='Pages.treino')),
            ],
        ),
    ]
