# Generated by Django 5.2 on 2025-07-16 04:23

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('plano_status', models.BooleanField(default=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('condicoes_medicas', models.CharField(blank=True, max_length=255, null=True)),
                ('ciclo_menstrual', models.CharField(blank=True, max_length=100, null=True)),
                ('medicamentos', models.CharField(blank=True, max_length=255, null=True)),
                ('lesoes', models.CharField(blank=True, max_length=255, null=True)),
                ('ocupacao', models.CharField(blank=True, max_length=100, null=True)),
                ('estilo_vida', models.CharField(blank=True, max_length=100, null=True)),
                ('pratica_esportes', models.CharField(blank=True, max_length=100, null=True)),
                ('pratica_exercicios', models.CharField(blank=True, max_length=100, null=True)),
                ('dias_disponiveis', models.CharField(blank=True, max_length=100, null=True)),
                ('horario_preferencia', models.CharField(blank=True, max_length=100, null=True)),
                ('exercicio_preferencia', models.CharField(blank=True, max_length=100, null=True)),
                ('info_adicional', models.CharField(blank=True, max_length=255, null=True)),
                ('tempo_atual_treino', models.CharField(blank=True, max_length=100, null=True)),
                ('tempo_destreinado', models.CharField(blank=True, max_length=100, null=True)),
                ('tempo_treino_anterior', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='GrupoMuscular',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'grupo muscular',
                'verbose_name_plural': 'grupos musculares',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Organizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da Avaliação')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Peso (kg)')),
                ('massa_muscular', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Massa Muscular (kg)')),
                ('gordura_percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Gordura (%)')),
                ('gorduraKg', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Gordura (Kg)')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Altura (m)')),
                ('peitoral', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('cintura', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('abdomen', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('quadril', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('braco_direito', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('braco_esquerdo', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('antebraco_direito', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('antebraco_esquerdo', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('coxa_direita', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('coxa_esquerda', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('panturrilha_direita', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('panturrilha_esquerda', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('dobra_peitoral', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('dobra_subescapular', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('dobra_axilar', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('dobra_triceps', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('dobra_abdominal', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('dobra_suprailiaca', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('dobra_coxa', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('postural_pescoco', models.CharField(blank=True, max_length=100)),
                ('postural_ombro', models.CharField(blank=True, max_length=100)),
                ('postural_quadril', models.CharField(blank=True, max_length=100)),
                ('postural_joelho', models.CharField(blank=True, max_length=100)),
                ('postural_tornozelo', models.CharField(blank=True, max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='avaliacoes_fotos/')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pages.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('grupo_muscular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios_principais', to='Pages.grupomuscular')),
                ('grupo_muscular_secundario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercicios_secundarios', to='Pages.grupomuscular')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='organizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pages.organizacao'),
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('nivel_acesso', models.CharField(choices=[('usuario', 'Usuário'), ('admin', 'Administrador'), ('master', 'Master')], default='usuario', max_length=10)),
                ('status_bloqueio', models.BooleanField(default=False)),
                ('primeiro_acesso', models.BooleanField(default=True)),
                ('organizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pages.organizacao')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='plano_tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pages.plano'),
        ),
        migrations.CreateModel(
            name='TreinoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('data_inicio', models.DateField(default=datetime.date.today)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True)),
                ('exercicios', models.JSONField(blank=True, default=list)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinos', to='Pages.aluno')),
            ],
        ),
    ]
