# Generated by Django 5.2 on 2025-06-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciciotreino',
            name='metodo',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='exerciciotreino',
            name='notas',
            field=models.TextField(blank=True),
        ),
    ]