# Generated by Django 5.2 on 2025-06-01 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0002_avaliacao_gordura'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='gordura',
            new_name='gorduraKg',
        ),
    ]
