# Generated by Django 5.2 on 2025-06-01 16:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0002_exerciciotreino_metodo_exerciciotreino_notas'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreinoPredefinido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('objetivo', models.CharField(blank=True, max_length=60)),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TreinoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('data_inicio', models.DateField(default=datetime.date.today)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinos_aluno', to='Pages.aluno')),
                ('template_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pages.treinopredefinido')),
            ],
        ),
        migrations.CreateModel(
            name='TreinoPredefExercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('series', models.PositiveIntegerField(blank=True, null=True)),
                ('repeticoes', models.PositiveIntegerField(blank=True, null=True)),
                ('carga', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('intervalo_seg', models.PositiveIntegerField(blank=True, null=True)),
                ('metodo', models.CharField(blank=True, max_length=30)),
                ('notas', models.TextField(blank=True)),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pages.exercicio')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='Pages.treinopredefinido')),
            ],
            options={
                'ordering': ['ordem'],
                'unique_together': {('template', 'exercicio', 'ordem')},
            },
        ),
        migrations.CreateModel(
            name='TreinoAlunoExercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('series', models.PositiveIntegerField(blank=True, null=True)),
                ('repeticoes', models.PositiveIntegerField(blank=True, null=True)),
                ('carga', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('intervalo_seg', models.PositiveIntegerField(blank=True, null=True)),
                ('metodo', models.CharField(blank=True, max_length=30)),
                ('notas', models.TextField(blank=True)),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pages.exercicio')),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='Pages.treinoaluno')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
    ]