# Generated by Django 5.2 on 2025-06-04 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0004_organizacao_aluno_organizacao_perfilusuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfilusuario',
            old_name='user',
            new_name='usuario',
        ),
    ]
