# Generated by Django 5.2 on 2025-06-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0005_rename_user_perfilusuario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='status_bloqueio',
            field=models.BooleanField(default=False),
        ),
    ]
