# Generated by Django 5.2 on 2025-06-05 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0006_perfilusuario_status_bloqueio'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='primeiro_acesso',
            field=models.BooleanField(default=False),
        ),
    ]
