# Generated by Django 5.2 on 2025-06-07 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0007_perfilusuario_primeiro_acesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='primeiro_acesso',
            field=models.BooleanField(default=True),
        ),
    ]
