# Generated by Django 5.2 on 2025-06-07 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0008_alter_perfilusuario_primeiro_acesso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='organizacoes',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='organizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pages.organizacao'),
        ),
    ]
