# Generated by Django 5.2 on 2025-06-20 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0003_treinopredefinido_treinopredefexercicio_treinoaluno_treinoalunoexercicio'),
        ('Pages', '0009_remove_perfilusuario_organizacoes_and_more'),
    ]

    operations = [
    ]
