# Generated by Django 5.2 on 2025-07-14 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0010_merge_20250619_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoMuscular',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'grupo muscular',
                'verbose_name_plural': 'grupos musculares',
                'ordering': ['nome'],
            },
        ),
        migrations.RemoveField(
            model_name='exercicio',
            name='categoria',
        ),
        migrations.AddField(
            model_name='exercicio',
            name='grupo_muscular_secundario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercicios_secundarios', to='Pages.grupomuscular'),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='grupo_muscular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios_principais', to='Pages.grupomuscular'),
        ),
    ]
