# Generated by Django 5.2.3 on 2025-07-13 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da Avaliação')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Peso (kg)')),
                ('massa_muscular', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Massa Muscular (kg)')),
                ('gordura_percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Gordura (%)')),
                ('gorduraKg', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Gordura (Kg)')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Altura (m)')),
                ('peitoral', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Peitoral (cm)')),
                ('cintura', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Cintura (cm)')),
                ('abdomen', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Abdômen (cm)')),
                ('quadril', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Quadril (cm)')),
                ('braco_direito', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Braço Direito (cm)')),
                ('braco_esquerdo', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Braço Esquerdo (cm)')),
                ('antebraco_direito', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Antebraço Direito (cm)')),
                ('antebraco_esquerdo', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Antebraço Esquerdo (cm)')),
                ('coxa_direita', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Coxa Direita (cm)')),
                ('coxa_esquerda', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Coxa Esquerda (cm)')),
                ('panturrilha_direita', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Panturrilha Direita (cm)')),
                ('panturrilha_esquerda', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Panturrilha Esquerda (cm)')),
                ('dobra_peitoral', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Dobra Peitoral (mm)')),
                ('dobra_subescapular', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Dobra Subescapular (mm)')),
                ('dobra_axilar', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Dobra Axilar Média (mm)')),
                ('dobra_triceps', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Dobra Tríceps (mm)')),
                ('dobra_abdominal', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Dobra Abdominal (mm)')),
                ('dobra_suprailiaca', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Dobra Supra Ilíaca (mm)')),
                ('dobra_coxa', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Dobra Coxa (mm)')),
                ('postural_pescoco', models.CharField(blank=True, max_length=100, verbose_name='Postural Pescoço')),
                ('postural_ombro', models.CharField(blank=True, max_length=100, verbose_name='Postural Ombro')),
                ('postural_quadril', models.CharField(blank=True, max_length=100, verbose_name='Postural Quadril')),
                ('postural_joelho', models.CharField(blank=True, max_length=100, verbose_name='Postural Joelho')),
                ('postural_tornozelo', models.CharField(blank=True, max_length=100, verbose_name='Postural Tornozelo')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='avaliacoes_fotos/', verbose_name='Foto da Avaliação')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.aluno')),
            ],
            options={
                'verbose_name': 'Avaliação Física',
                'verbose_name_plural': 'Avaliações Físicas',
                'ordering': ['-data'],
            },
        ),
    ]
