# Generated by Django 5.2.3 on 2025-07-13 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoMuscular',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'grupo muscular',
                'verbose_name_plural': 'grupos musculares',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('grupo_muscular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios_principais', to='exercicios.grupomuscular')),
                ('grupo_muscular_secundario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercicios_secundarios', to='exercicios.grupomuscular')),
            ],
        ),
    ]
