# Generated by Django 5.2.3 on 2025-07-13 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
        ('exercicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rotina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex.: Hipertrofia Lower/Upper – 8 semanas', max_length=120)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotinas', to='alunos.aluno')),
            ],
            options={
                'verbose_name': 'Rotina',
                'verbose_name_plural': 'Rotinas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RotinaExercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')])),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('series', models.PositiveIntegerField(blank=True, null=True)),
                ('repeticoes', models.PositiveIntegerField(blank=True, null=True)),
                ('carga', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('intervalo_seg', models.PositiveIntegerField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercicios.exercicio')),
                ('rotina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotina_exercicios', to='treinos.rotina')),
            ],
            options={
                'verbose_name': 'Exercício da Rotina',
                'verbose_name_plural': 'Exercícios da Rotina',
                'ordering': ['dia_semana', 'ordem'],
                'unique_together': {('rotina', 'dia_semana', 'ordem')},
            },
        ),
        migrations.AddField(
            model_name='rotina',
            name='exercicios',
            field=models.ManyToManyField(related_name='rotinas', through='treinos.RotinaExercicio', to='exercicios.exercicio'),
        ),
    ]
