MUSCLE_PRESETS = {
    'trapezius':  'Trapézio',
    'chest':      'Peitoral',
    'back':       'Costas',
    'shoulders':  'Ombros',
    'biceps':     'Bíceps',
    'triceps':    'Tríceps',
    'brachialis': 'Braquial',
    'forearms':   'Antebraços',
    'abs':        'Abdômen',
    'obliques':   'Oblíquos',
    'lombar':     'Lombar',
    'iliopsoas':  'Iliopsoas',
    'glutes':     'Glúteos',
    'quadriceps': 'Quadríceps',
    'hamstrings': 'Posterior',
    'calves':     'Panturrilhas',
    'adductors':  'Adutores',
    'abductors':  'Abdutores',
    'cardio':     'Cardio',
}
